### ISSUE TITLE
Remove FTP drop 

### ISSUE THREAD

**Issue by ghost** [berman-lab/ymap#28] opened 2016-07-18 07:14 UTC
from user.register_server.php lines 29-31 in user.register_server.php.

**Comment by vladimirg** [comment] 2016-07-19 09:09
Turns out this is a duplicate of #22 , so closing this. As stated there, the correct way to remote the FTP drop is to reverse-commit the FTP-related commits, or at least go over them to make sure we got everything.

**Closed as completed by vladimirg** 2016-07-19 09:09 UTC
